version: "3.9"

# This top-level compose file is now split per-VM. See:
#  - docker-compose.vm1.yml
#  - docker-compose.vm2.yml
#  - docker-compose.vm3.yml
# Keeping this file as a pointer to the new per-VM files.

services: {}

volumes: {}

networks: {}
