# Supabase Helm Chart Values for Patroni HA PostgreSQL Cluster
# This configuration overrides default values to connect Supabase services to an external Patroni PostgreSQL cluster

secret:
  jwt:
    anonKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MVc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
    serviceKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q
    secret: your-super-secret-jwt-token-with-at-least-32-characters-long
  smtp:
    username: your-mail@example.com
    password: example123456
  dashboard:
    username: supabase
    password: password
  db:
    username: postgres
    password: password  # Must match POSTGRES_PASSWORD in patroni-secrets
    database: postgres
  analytics:
    apiKey: your-super-secret-and-long-logflare-key

# Disable built-in PostgreSQL - using external Patroni cluster
db:
  enabled: false

# Override database connections for all services to use Kubernetes HAProxy
auth:
  environment:
    DB_HOST: postgres-master.hapostgresql.svc.cluster.local
    DB_USER: postgres
    API_EXTERNAL_URL: http://example.com
    GOTRUE_SITE_URL: http://example.com
    GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
    GOTRUE_MAILER_AUTOCONFIRM: "true"
    GOTRUE_SMTP_ADMIN_EMAIL: "your-mail@example.com"
    GOTRUE_SMTP_HOST: "smtp.example.com"
    GOTRUE_SMTP_PORT: "587"
    GOTRUE_SMTP_SENDER_NAME: "your-mail@example.com"

rest:
  environment:
    DB_HOST: postgres-master.hapostgresql.svc.cluster.local
    DB_USER: postgres

realtime:
  environment:
    DB_HOST: postgres-master.hapostgresql.svc.cluster.local
    DB_USER: postgres

meta:
  environment:
    DB_HOST: postgres-master.hapostgresql.svc.cluster.local
    DB_USER: postgres

storage:
  environment:
    DB_HOST: postgres-master.hapostgresql.svc.cluster.local
    DB_USER: postgres

analytics:
  environment:
    DB_HOST: postgres-master.hapostgresql.svc.cluster.local
    DB_USERNAME: postgres

functions:
  environment:
    DB_HOST: postgres-master.hapostgresql.svc.cluster.local
    DB_USERNAME: postgres

# Studio configuration
studio:
  environment:
    STUDIO_DEFAULT_ORGANIZATION: "My Organization"
    STUDIO_DEFAULT_PROJECT: "My Project"
    SUPABASE_PUBLIC_URL: http://example.com/
    NEXT_PUBLIC_ENABLE_LOGS: "true"
    NEXT_ANALYTICS_BACKEND_PROVIDER: postgres

# Kong ingress configuration
kong:
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: example.com
        paths:
          - path: /
            pathType: Prefix
